---
title: "Personal Takeaways"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here are some informal things I learned from the summer. Sorry, no science here! Just ranting and philosophizing. 

## On developing my own project (& how being lost made me independent)

A couple months before I started at Fred Hutch, Rob Amezquita asked me what I wanted to do with my summer.

ME! He asked me! Who am I to know? Honestly! I don't know anything at all! It was like a math teacher walking into math class on the first day and asking the class what topic they want to be taught. Isn't that their job to know? I don't even know what the options were, much less which ones I could handle.

And yet, that was how the summer went. Sometimes Rob would give me helpful guiding advice, but mostly he just let me work and taught me how to do basic technical stuff when I couldn't get something to work. When I would ask him if something sounded like a good idea, he would almost always be enthusiastic. While this was encouraging, it did not much help me sort good ideas from bad ones. I went on several tangents throughout the summer on projects that either had zero potential, or were well outside of my scope. I spent the majority of the summer feeling lost and confused, and in some ways, it was terrible. 

I remember how amazing it felt every time I felt like I managed to latch onto a good idea, before invariably finding out that it was harder and more complex than I had guessed. There is something truly humbling about getting excited about an idea, exploring it, and then reluctantly concluding that it really is just not going to work. Especially if the reason it doesn't work is because you can't for the life of you figure it out.

This project made me realize what it really means to be independent. The independence I found this summer was the sort of independence where you don't know where each path leads. I had to make hard decisions using only what little experience or intuition I had. I was not only the architect of my project, but I had no blueprint. I think that's the crux of it. I had no sense of the bigger picture, and that was a new feeling to me. Luckily, I did not have a lot at stake.

Although I didn't enjoy the sensation of being lost, I did learn a lot. I learned how to think critically, not just about what I was doing, but why I was doing it, and where it fit into the bigger picture. I learned that good questions require creativity not only to tackle, but to find. I learned that science has dead ends, and that they are somehow far more frustrating than they sound. I learned that talking to people is good for identifying bad ideas before they become time-wasters, as well as discovering unexpected paths forward.

And eventually, I did find something interesting that I had some ability to tackle. The project became mine in a way that no project ever has before. All of the stumbling I did proved to me that for the most part, I had been engineering my own way forward. The clarity I began to feel was invigorating. After feeling so lost for so long, even my relatively shitty project felt incredibly real. I could finally throw myself into something and have some faith that I wasn't going to have to scrap everything within a week. And then, the unthinkable happened: it actually became fun! (Head to the section on my final presentation to see how that turned out).


## On machine learning (& why I hate it)

Machine learning is powerful. So so powerful. Many tasks that used to require a human can now be accomplished through machine learning, such as image and speech recognition. It can even do some things far better than humans, such as play chess.

I don't specifically mind that machine learning is powerful. What frustrates me is that it is so opaque. Somehow, the best chess programs in the world aren't those that look into the future in predictable or human-like ways. Rather, they are the programs which do some confusing, untraceable analysis and pop an answer out of nowhere. 

I think these attributes make them unpredictable to use, difficult to analyze, and unsatisfying to build. They have random weaknesses and confusing strengths, and it is rarely clear the best way to build them. They act up in certain cases, and seemingly have a mind of their own. They go against everything I believed about computers. I thought programming was beautiful, and logical, and that with enough inspection, you could really understand what every single process was doing and why. Then suddenly, the pinnacle of computing intelligence and the focus of most active research becomes this random and messy process called machine learning.

What bothers me is that for some tasks, the messier and more arbitrary methods just work better. I feel annoyed that I have to work with them just because they are so randomly powerful. They seem so fickle. They start with nothing, and I have to feed them data and wait for them to learn and grow on their own, and then eventually they decide whether or not to become useful. It takes away much of the careful engineering aspect of programming that I enjoy so much.

Of course, you can still be rigorous with the models, and do careful testing to see which architectures and hyperparameters work best. I just feel like the black box aspect of it permeates my perception of these techniques. I admit that machine learning is important to understand, and in several respects may be the future of programming. This is why I am learning it. But make no mistake, I wish it had never been invented.

## On my final presentation (& how the truth hurts)

I love giving presentations. I usually feel a little nervous before I start, but then I ease into it quickly and don't look back. For years, I've received lavish praise on my enthusiastic presence and clear storytelling during presentations. I enjoy breaking concepts down for people and helping them understand, and presenting is fun because I can gauge reactions as I go and show off my public speaking skills. 

When I found out I was giving a research presentation to the lab, I was eager to prove myself. I worked on my presentation for about a week, and thought it was great. I practiced several times in front of my parents, who (unsurprisingly) told me it was amazing and offered a few tips. 

When the day came to present it, I thought it went super well. I walked through my background smoothly, explained my work, and discussed how it might be useful.

I was then surprised when my mentors sat me down afterwards and told me that it wasn't very good. They were quick to say that my presentation itself was fine, and that they thought the lab likely enjoyed it. But they were also clear that it was NOT a good presentation... it had too much fluff, too much hand-wavey oversimplification, and overall tried to do more than it should have.

In retrospect, I completely agree. In service of 'telling a story,' I exaggerated certain things which I simply did not have adequate proof for. My presentation was an idealistic jaunt through my discussion section, and many of the statements I made would certainly raise eyebrows amongst those who knew better. Nothing was blatantly incorrect as far as I can tell, but much of it was just overeager, and some things I said had no real proof behind them. 

As I processed what they said, I felt less and less like a scientist, and more like a vapid journalist, jumping straight for conclusions while ignoring many important naunces.

Afterwards, Etienne said something that hit me: "when I was younger, I never reached a conclusion until I had to." Or something along those lines. What I took from it was that I should never have tried to conclude all the things I did. I should have presented my work and my results, and talked about what I thought the implications were. No simplifying or assuming or guessing.

I felt terrible after that presentation. It really changed everything for me. I tried not to let it on to anybody, but I just felt so stupid and insecure. Of course I had no business trying to tell a story as if I knew anything. I was just an undergrad intern, trying to dip my toes in a field people had spent a lifetime studying.

I think it was that day that I lost a lot of motivation for my project. Before that presentation, I looked at my work and saw a story. I saw the big picture, and my project was like a little piece of that big jigsaw. It wasn't a lot, but I felt like I could actually make a difference in the field. 

Afterwards, I looked at it and saw only a mediocre attempt by a starry-eyed kid. Which is always what it was. As a student, particularly one without a strong biology or statistics background, there was little I could do with a single summer, no matter how hard I worked. To even get started in scientific research requires a lot of time and experience, and although enthusiasm is important, I learned that it is no substitute for the others. I'm smart, and I can work hard, but sometimes the truth is hard. I was simply never meant to accomplish much this summer.

This is not at all to say I contributed nothing. I think the stuff I was working on does have some potential, and there are things to be learned even from the progress I made so far. I just also needed to be realistic about it and not make it out to be something it wasn't.

## On my experience with Rob and the RG Lab (& how they were awesome)

The RG Lab was very kind to take me in over the summer. They even paid me surprisingly well (as in a non-zero amount). I think the most stunning thing was that I did enjoy my time in the lab, despite not particularly loving the biological research aspect of it.

I worked in a smaller office with Rob Amezquita and Etienne Becht, so I spent a lot of time interacting with the two of them. Rob especially I spent a lot of time with, and had a good time doing so. He is fun and enthusiastic, and silly. Since the summer ended, I have enjoyed staying in contact with him.

Throughout the lab, I felt respected and heard and valued, to a far greater extent than my ideas and skills actually merited. It was both exciting and terrifying to be treated essentially as an equal by scientists who had orders of magnitude more experience than I. Furthermore, my non-zero salary proved, at least to some extent, that their money was where their mouth was. That mood and atmosphere was inspiring, and I tried my best to be worthy of it. At the same time, it made me nervous. If I had felt that nobody expected anything of me, I would not have felt nearly so guilty upon realizing how little I really accomplished.

My experience with Rob and the lab showed me how important it is for me to work with people I like, and to feel respected. I wanted to go to work each day not because I was particularly passionate about the work, but because I wanted to work with Rob and contribute to the lab. As I explained in other sections, I had a rocky relationship with the work itself. I would not have had the will to keep at it without the support and friendship of the team around me.

I used to believe that if I enjoyed my work enough, it wouldn't matter who I was working with. I realize now that both are important.

